# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: >
    (?x)^(
    renv/library/.*|
    docs/.*
    )$
repos:
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
    -   id: markdownlint
        args: ["--fix"]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ["--maxkb", "80000"]
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
    - id: shellcheck

-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
    -   id: style-files
        args: ["--style_pkg", "styler", "--style_fun", "tidyverse_style"]
        exclude: "renv/library/.*"
    -   id: parsable-R
        exclude: "renv/library/.*"
    -   id: no-browser-statement
        exclude: "renv/library/.*"
